language: node_js
sudo: false
node_js:
  - 0.10
before_script:
  - npm install
  - npm install -g codeclimate-test-reporter
script: 
  - jasmine-node spec/ --color --verbose
after_script:
  - npm run coverage
  - codeclimate-test-reporter < coverage/lcov.info
addons:
  code_climate:
    repo_token: aa712832c53be457394a70da8a40f79ce80301c0ca6f7fbfebf8c003a3828473